In [2]:
import numpy as np
import pandas as pd

In [9]:
countries = pd.read_csv('Datasets/countries-of-the-world.csv')
countries.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [3]:
def square(x):
    return x*x

print(square(2))
print(square(25))

4
625

In [17]:
countries['GDP ($ per capita)'].apply(lambda x: x*x)
countries['GDP ($ per capita)'].apply(lambda row: row['Area (sq.mi.)'] / row['Population'], axis=1)

# Axis = 1 is for row
# Axis = 0 is for column

TypeError: <lambda>() got an unexpected keyword argument 'axis'

# Loading Data into Pandas

In [14]:
import pandas as pd

grades = pd.read_csv('Datasets/grades.csv')

grades

      James Abbott       Good   87   Pass   100   93        76        85
0       Jane Baker       Good   92   Pass    95   97        84        82
1  George Costello   Adequate   83   Pass   100   91   missing        88
2      Susan Davis       Good   79   Pass   100   86        81        90
3    Jared Erikson    Perfect   96   Pass    85   90        87        79
4  Samantha Fisher       Fail   54   Fail    60   40        62   missing
5     Isaac Gibson   Adequate   76   Pass    95   89   missing        72
6   Emily Harrison       Good   88   Pass   100  100        93        81
7     Peter Ingram   Adequate   90   Fail   100   94        79        80
8  Michael Jackson    Perfect   89   Pass    95   99        84        87

In [15]:
grades = pd.read_csv('Datasets/grades.csv', header = None)

column_names = ['NAM', 'ATT', 'HON', 'PRP', 'PRC', 'PRF', 'MID', 'FIN']
grades = pd.read_csv('Datasets/grades.csv', header = None, names=column_names)
grades

               NAM        ATT  HON    PRP  PRC  PRF       MID       FIN
0     James Abbott       Good   87   Pass  100   93        76        85
1       Jane Baker       Good   92   Pass   95   97        84        82
2  George Costello   Adequate   83   Pass  100   91   missing        88
3      Susan Davis       Good   79   Pass  100   86        81        90
4    Jared Erikson    Perfect   96   Pass   85   90        87        79
5  Samantha Fisher       Fail   54   Fail   60   40        62   missing
6     Isaac Gibson   Adequate   76   Pass   95   89   missing        72
7   Emily Harrison       Good   88   Pass  100  100        93        81
8     Peter Ingram   Adequate   90   Fail  100   94        79        80
9  Michael Jackson    Perfect   89   Pass   95   99        84        87