# Web Scraping
Look for tables within websites
- Pandas
- BeautifulSoup

# Web Scraping with Pandas

In [13]:
!pip install lxml
!pip install requests

Requirement already satisfied: lxml in c:\users\caelc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (6.0.2)

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: C:\Users\caelc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.4-cp311-cp311-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ---------------------------------------- 0.0/64.7 kB ? eta -:--:--
   ------------------------------------- -- 61.4/64.7 kB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 64.7/64.7 kB 1.2 MB/s eta 0:00:00
Downloading certifi-2026.1.4-py3-none-any.whl (152 kB)
   ---------------------------------------- 0.0/152.9 kB ? eta -:--:--
   ---------------------------------------- 152.9/152.9 kB 8.9 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.4-cp311-cp311-win_amd64.whl (106 kB)
   ---------------------------------------- 0.0/107.0 kB ? eta -:--:--
   ---------------------------------------- 107.0/107.0 kB 6.4 MB/s eta 0:00:00
Downloading idna-3.11-py3-none-any.whl (71 kB)
   ---------------------------------------- 0.0/71.0 kB ? eta -:--:--
   ---------------------------------------- 71.0/71.0 kB 4.1 MB/s eta 0:00:00
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ---------------------------------------- 0.0/131.6 kB ? eta -:--:--
   ---------------------------------------- 131.6/131.6 kB 7.6 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
Successfully installed certifi-2026.1.4 charset_normalizer-3.4.4 idna-3.11 requests-2.32.5 urllib3-2.6.3

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: C:\Users\caelc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd
import requests
url = "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings_(film_series)"
headers = {"User-Agent" : "Mozilla/5.0 (WIndows NT 10.0; Win64; x64)"}
response = requests.get(url, headers=headers)
print(response.text)
# lotr = pd.read_html(url)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" lang="en" dir="ltr">
<head>
<meta charset="UTF-8">
<title>The Lord of the Rings (film series) - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"dab4b98e-1c81-4797-a56e-e700694a54b3","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"The_Lord_of_the_Rings_(film_series)","wgTitle":"The Lord of the Rings (film series)","wgCurRevisionId":1333986257,"wgRevisionId":1333986257,"wgArticleId":414113,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 French-language sources (fr)","Articles with short description","Short description is different from Wikidata","Good articles","Use New Zealand English from July 2021","All Wikipedia articles written in New Zealand English","Use dmy dates from April 2024","Template film date with 3 release dates","Pages using multiple image with auto scaled images","Commons category link is on Wikidata","Pages using IMDb title with no id set","2001 films","The Lord of the Rings (film series)","Adventure film series","Film series introduced in 2001","New Line Cinema franchises","Films based on The Lord of the Rings","Fantasy film series","American film series","New Zealand film series","Film series based on fantasy novels","Film series based on British novels"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"The_Lord_of_the_Rings_(film_series)","wgRelevantArticleId":414113,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":100000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q190214","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgGEUseMetricsPlatformExtension":true,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]},"wgTestKitchenUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession","ext.xLab","ext.testKitchen"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta name="ResourceLoaderDynamicStyles" content="">
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">
<meta name="generator" content="MediaWiki 1.46.0-wmf.12">
<meta name="referrer" content="origin">
<meta name="referrer" content="origin-when-cross-origin">
<meta name="robots" content="max-image-preview:standard">
<meta name="format-detection" content="telephone=no">
<meta name="viewport" content="width=1120">
<meta property="og:title" content="The Lord of the Rings (film series) - Wikipedia">
<meta property="og:type" content="website">
<link rel="preconnect" href="//upload.wikimedia.org">
<link rel="alternate" type="application/x-wiki" title="Edit this page" href="/w/index.php?title=The_Lord_of_the_Rings_(film_series)&amp;action=edit">
<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">
<link rel="icon" href="/static/favicon/wikipedia.ico">
<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (en)">
<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd">
<link rel="canonical" href="https://en.wikipedia.org/wiki/The_Lord_of_the_Rings_(film_series)">
<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">
<link rel="alternate" type="application/atom+xml" title="Wikipedia Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom">
<link rel="dns-prefetch" href="//meta.wikimedia.org" />
<link rel="dns-prefetch" href="auth.wikimedia.org">
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-The_Lord_of_the_Rings_film_series rootpage-The_Lord_of_the_Rings_film_series skin-vector-2022 action-view">
<div id="mw-aria-live-region" class="mw-aria-live-region" aria-live="polite"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
	<header class="vector-header mw-header no-font-mode-scale">
		<div class="vector-header-start">
			<nav class="vector-main-menu-landmark" aria-label="Site">

<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Main menu" >
	<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Main menu"  >
	<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>

<span class="vector-dropdown-label-text">Main menu</span>
	</label>
	<div class="vector-dropdown-content">


				<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">

<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">
	<div
	class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"
	data-feature-name="main-menu-pinned"
	data-pinnable-element-id="vector-main-menu"
	data-pinned-container-id="vector-main-menu-pinned-container"
	data-unpinned-container-id="vector-main-menu-unpinned-container"
>
	<div class="vector-pinnable-header-label">Main menu</div>
	<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
	<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>


<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >
	<div class="vector-menu-heading">
		Navigation
	</div>
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">

			<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Main_Page" title="Visit the main page [z]" accesskey="z"><span>Main page</span></a></li><li id="n-contents" class="mw-list-item"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Special:Random" title="Visit a randomly selected article [x]" accesskey="x"><span>Random article</span></a></li><li id="n-aboutsite" class="mw-list-item"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li id="n-contactpage" class="mw-list-item"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
		</ul>

	</div>
</div>


<div id="p-interaction" class="vector-menu mw-portlet mw-portlet-interaction"  >
	<div class="vector-menu-heading">
		Contribute
	</div>
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">

			<li id="n-help" class="mw-list-item"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li id="n-introduction" class="mw-list-item"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]" accesskey="r"><span>Recent changes</span></a></li><li id="n-upload" class="mw-list-item"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Special:SpecialPages"><span>Special pages</span></a></li>
		</ul>

	</div>
</div>

</div>

				</div>

	</div>
</div>

		</nav>

<a href="/wiki/Main_Page" class="mw-logo">
	<img class="mw-logo-icon" src="/static/images/icons/enwiki-25.svg" alt="" aria-hidden="true" height="50" width="50">
	<span class="mw-logo-container skin-invert">
		<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;">
		<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" width="140" height="11" style="width: 8.75em; height: 0.6875em;">
	</span>
</a>

		</div>
		<div class="vector-header-end">

<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">
	<a href="/wiki/Special:Search" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Search Wikipedia [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>

<span>Search</span>
	</a>
	<div class="vector-typeahead-search-container">
		<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
			<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">
				<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">
					<div class="cdx-text-input cdx-text-input--has-start-icon">
						<input
							class="cdx-text-input__input mw-searchInput" autocomplete="off"
							 type="search" name="search" placeholder="Search Wikipedia" aria-label="Search Wikipedia" autocapitalize="none" spellcheck="false" title="Search Wikipedia [f]" accesskey="f" id="searchInput"
							>
						<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
					</div>
					<input type="hidden" name="title" value="Special:Search">
				</div>
				<button class="cdx-button cdx-search-input__end-button">Search</button>
			</form>
		</div>
	</div>
</div>

			<nav class="vector-user-links vector-user-links-wide" aria-label="Personal tools">
	<div class="vector-user-links-main">

<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>


<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>

	<nav class="vector-appearance-landmark" aria-label="Appearance">

<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Change the appearance of the page&#039;s font size, width, and color" >
	<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Appearance"  >
	<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>

<span class="vector-dropdown-label-text">Appearance</span>
	</label>
	<div class="vector-dropdown-content">


			<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">

			</div>

	</div>
</div>

	</nav>

<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>


<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">
			<li id="pt-sitesupport-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" class=""><span>Donate</span></a>
</li>
<li id="pt-createaccount-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="/w/index.php?title=Special:CreateAccount&amp;returnto=The+Lord+of+the+Rings+%28film+series%29" title="You are encouraged to create an account and log in; however, it is not mandatory" class=""><span>Create account</span></a>
</li>
<li id="pt-login-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="/w/index.php?title=Special:UserLogin&amp;returnto=The+Lord+of+the+Rings+%28film+series%29" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o" class=""><span>Log in</span></a>
</li>


		</ul>

	</div>
</div>

	</div>

<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item"  title="Log in and more options" >
	<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Personal tools"  >
	<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>

<span class="vector-dropdown-label-text">Personal tools</span>
	</label>
	<div class="vector-dropdown-content">



<div id="p-personal" class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item"  title="User menu" >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


In [19]:
data = response.text
tables = pd.read_html(data) # Gives back an array of tables
display(tables[5])

C:\Users\caelc\AppData\Local\Temp\ipykernel_30172\3588129937.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(data)

,Film,Rotten Tomatoes,Metacritic,CinemaScore[95]
0,The Fellowship of the Ring,92% (8.20/10 average rating) (237 reviews)[96],92/100 (34 reviews)[97],A−
1,The Two Towers,95% (8.50/10 average rating) (260 reviews)[98],87/100 (39 reviews)[99],A
2,The Return of the King,94% (8.70/10 average rating) (282 reviews)[100],94/100 (41 reviews)[101],A+

In [22]:
lotr_soundtrack = tables[3]
lotr_box_office = tables[4]
lotr_ratings = tables[5]

new_col_names = []

for col in lotr_box_office.columns:
    new_col_names.append(col[2]) # Get the third element of the tuple

lotr_box_office.columns = new_col_names

In [23]:

display(lotr_box_office)
display(lotr_soundtrack)
display(lotr_ratings)

,Film,U.S. release date,U.S. and Canada,Other territories,Worldwide,Rank,Peak,Rank,Peak,Budget,Ref(s)
0,The Fellowship of the Ring,19 December 2001,"$319,372,078","$568,468,333","$887,840,411",91.0,9.0,77.0,5.0,$93 million,[64][65][66]
1,The Two Towers,18 December 2002,"$345,518,923","$592,392,292","$937,911,215",72.0,7.0,71.0,4.0,$94 million,[67][68][69]
2,The Return of the King,17 December 2003,"$381,878,219","$756,308,664","$1,138,186,883",51.0,6.0,31.0,2.0,$94 million,[70][71][72]
3,Total,Total,"$1,046,769,220","$1,917,169,289","$2,963,938,509",NaN,NaN,NaN,NaN,$281 million,[note 1]

,Title,U.S. release date,Length,Composer,Label
0,The Fellowship of the Ring: Original Motion Pi...,20 November 2001,71:29,Howard Shore,Reprise Records
1,The Two Towers: Original Motion Picture Soundt...,10 December 2002,72:46,Howard Shore,Reprise Records
2,The Return of the King: Original Motion Pictur...,25 November 2003,72:05,Howard Shore,Reprise Records

,Film,Rotten Tomatoes,Metacritic,CinemaScore[95]
0,The Fellowship of the Ring,92% (8.20/10 average rating) (237 reviews)[96],92/100 (34 reviews)[97],A−
1,The Two Towers,95% (8.50/10 average rating) (260 reviews)[98],87/100 (39 reviews)[99],A
2,The Return of the King,94% (8.70/10 average rating) (282 reviews)[100],94/100 (41 reviews)[101],A+

## Read tables from HTML using BeautifulSoup

In [31]:
!pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Collecting beautifulsoup4 (from bs4)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->bs4)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\caelc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
   ---------------------------------------- 0.0/107.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/107.7 kB ? eta -:--:--
   ----------- --------------------------- 30.7/107.7 kB 660.6 kB/s eta 0:00:01
   -------------------------------------- - 102.4/107.7 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 107.7/107.7 kB 1.0 MB/s eta 0:00:00
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4, bs4
Successfully installed beautifulsoup4-4.14.3 bs4-0.0.2 soupsieve-2.8.3

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: C:\Users\caelc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [38]:
import requests
from bs4 import BeautifulSoup
url = "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings_(film_series)"

headers = {"User-Agent" : "Mozilla/5.0 (WIndows NT 10.0; Win64; x64)"}
response = requests.get(url, headers=headers)

data = response.text

soup = BeautifulSoup(data, 'lxml')
prettified_data = soup.prettify()
print(prettified_data)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   The Lord of the Rings (film series) - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"dab4b98e-1c81-4797-a56e-e700694a54b3","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"The_Lord_of_the_Rings_(film_series)","wgTitle":"The Lord of the Rings (film series)","wgCurRevisionId":1333986257,"wgRevisionId":1333986257,"wgArticleId":414113,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 French-language sources (fr)","Articles with short description","Short description is different from Wikidata","Good articles","Use New Zealand English from July 2021","All Wikipedia articles written in New Zealand English","Use dmy dates from April 2024","Template film date with 3 release dates","Pages using multiple image with auto scaled images","Commons category link is on Wikidata","Pages using IMDb title with no id set","2001 films","The Lord of the Rings (film series)","Adventure film series","Film series introduced in 2001","New Line Cinema franchises","Films based on The Lord of the Rings","Fantasy film series","American film series","New Zealand film series","Film series based on fantasy novels","Film series based on British novels"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"The_Lord_of_the_Rings_(film_series)","wgRelevantArticleId":414113,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":100000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q190214","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgGEUseMetricsPlatformExtension":true,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]},"wgTestKitchenUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession","ext.xLab","ext.testKitchen"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.46.0-wmf.12" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="The Lord of the Rings (film series) - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/index.php?title=The_Lord_of_the_Rings_(film_series)&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/The_Lord_of_the_Rings_(film_series)" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch"/>
  <link href="auth.wikimedia.org" rel="dns-prefetch"/>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-The_Lord_of_the_Rings_film_series rootpage-The_Lord_of_the_Rings_film_series skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a href="/wiki/Special:SpecialPages">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2">
           <a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2">

In [ ]:
prettified_data.find_all('b')

In [ ]:
soup.find_all('table')[5]

## Loading Excel Data

In [27]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.9 kB 660.6 kB/s eta 0:00:01
   ----------- --------------------------- 71.7/250.9 kB 787.7 kB/s eta 0:00:01
   ---------------------------------------  245.8/250.9 kB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 1.7 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: C:\Users\caelc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [29]:

grades = pd.read_excel("./Datasets/grades3.xlsx", skiprows=10)
display(grades)

               NAM        ATT   HOM    PRP   PRC   PRF       MID       FIN
0     James Abbott       Good    87   Pass   100    93        76        85
1       Jane Baker       Good    92   Pass    95    97        84        82
2  George Costello   Adequate    83   Pass   100    91   missing        88
3      Susan Davis       Good    79   Pass   100    86        81        90
4    Jared Erikson    Perfect    96   Pass    85    90        87        79
5  Samantha Fisher       Fail    54   Fail    60    40        62   missing
6     Isaac Gibson   Adequate    76   Pass    95    89   missing        72
7   Emily Harrison       Good    88   Pass   100   100        93        81
8     Peter Ingram   Adequate    90   Fail   100    94        79        80
9  Michael Jackson    Perfect    89   Pass    95    99        84        87